name: Firmware CI

"on":
  pull_request:
    branches:
      - master
    paths:
      - 'firmware/**'
      - 'scripts/**'
      - '.github/workflows/**'

jobs:
  build:
    uses: ./.github/workflows/firmware-build-reusable.yml
